### ISSUE TITLE
The expandableContent glitches before being hidden

### ISSUE THREAD

**Issue by nutchanon-c** [torbenkeller/expandable_bottom_sheet#23]
When I switch to the page, the expandableContent glitches and is shown at he top of the screen for a split second before it is being hidden correctly inside the bottom sheet.

**Comment by fikriprayoga1** [comment]
this usually because you have observer or change state on parent without static value key on parent widget. So, when you change state, that make expandable flicker because your parent widget of axpandble widget not use static valuekey

**Comment by timbotimbo** [comment]
This plugin calculates the required dimensions after the first build method.
Because of that it shows up in the wrong location on the first frame, and immediately collapses after that.


If you set a breakpoint in `raw_expandable_bottom_sheet.dart` -> `_afterUpdateWidgetBuild`, you can spot this (third picture).


<table>
<tr><td>Expanded</td>
<td>Collapsed</td>
<td>First frame</td>
</tr>
<tr><td>

![Expanded](https://user-images.githubusercontent.com/11444698/184172054-454e8b59-232e-45bc-a8a5-99c13b68efea.png) 
</td>

<td>

![Collapsed](https://user-images.githubusercontent.com/11444698/184172136-fafe69df-581e-49cc-967b-b98604b06b1c.png)
</td>
<td>

![Screenshot_1660229040](https://user-images.githubusercontent.com/11444698/184172535-ca7d3a34-79da-4658-84dd-0e97df088413.png) </td>
</tr>
</table>

A quick fix is to move the bottomsheet down in the build method of the plugin.

You can move the bottomsheet offscreen at the bottom for that first frame.  (Now the persistent part is offscreen for the first frame, and pops in at the bottom)
```dart
/* raw_expandable_bottom_sheet.dart */

 @override
 Widget build(BuildContext context) {
     // adjust the offset to move the bottomsheet down in the first frame
    _positionOffset ??= MediaQuery.of(context).size.height; 
```

If you use `persistentContentHeight` instead of `persistentHeader` this is even cleaner, with no movement in the first couple of frames.
```dart
/* raw_expandable_bottom_sheet.dart */

 @override
 Widget build(BuildContext context) {
     // adjust the offset to move the bottomsheet down in the first frame
    _positionOffset ??= MediaQuery.of(context).size.height - widget.persistentContentHeight;
```

**Comment by vixez** [comment]
I have the same issue, for now I hide the first frame by using `Opacity` with `AfterLayoutMixin`

```
class _MyState
    extends ConsumerState<TabRecognitionsCreateSelectUsers>
    with AfterLayoutMixin<TabRecognitionsCreateSelectUsers> {
  bool showExpandableContent = false;

  @override
  FutureOr<void> afterFirstLayout(BuildContext context) {
    setState(() {
      showExpandableContent = true;
    });
  }
```

```
        persistentHeader: Opacity(
          opacity: showExpandableContent ? 1.0 : 0.0,
```

```
        expandableContent: Opacity(
          opacity: showExpandableContent ? 1.0 : 0.0,
```

**Comment by PaMcD** [comment]
I'm having a similar issue but the afterFirstLayout fix doesnt work as i have a future builder so its not the 1st layout thats its gets created on, so thus doesnt work (i think?)

modifying raw_expandable_bottom_sheet.dart as suggested didnt seem to work either.

Any ideas?

**Comment by nutchanon-c** [comment]
> I have the same issue, for now I hide the first frame by using `Opacity` with `AfterLayoutMixin`
> 
> ```
> class _MyState
>     extends ConsumerState<TabRecognitionsCreateSelectUsers>
>     with AfterLayoutMixin<TabRecognitionsCreateSelectUsers> {
>   bool showExpandableContent = false;
> 
>   @override
>   FutureOr<void> afterFirstLayout(BuildContext context) {
>     setState(() {
>       showExpandableContent = true;
>     });
>   }
> ```
> 
> ```
>         persistentHeader: Opacity(
>           opacity: showExpandableContent ? 1.0 : 0.0,
> ```
> 
> ```
>         expandableContent: Opacity(
>           opacity: showExpandableContent ? 1.0 : 0.0,
> ```

This one solved my issue. Thank you
